### ISSUE TITLE
Building two (or more) more docker images causes error "The specified item already exists in the keychain."

### ISSUE THREAD

**Issue by advanderveer** [pulumi/pulumi-docker#362]
### What happened?

Trying to build two docker images (for the same repo) in a single `pulumi up` will cause the following error: 

```
Error saving credentials: error storing credentials - err: exit status 1, out: `error storing credentials - err: exit status 1, out: `The specified item already exists in the keychain.``
```

### Steps to reproduce

```Go
package main

import (
	"encoding/base64"
	"fmt"
	"strings"

	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/ecr"
	"github.com/pulumi/pulumi-docker/sdk/v3/go/docker"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func run(ctx *pulumi.Context) (err error) {
	var (
		repo *ecr.Repository
		info docker.ImageRegistryOutput
	)

	if repo, err = ecr.NewRepository(ctx, "dockerbug", &ecr.RepositoryArgs{
		ImageTagMutability: pulumi.StringPtr("IMMUTABLE"),
	}); err != nil {
		return fmt.Errorf("failed to create repo: %w", err)
	}

	info = repo.RegistryId.ApplyT(func(id string) (r docker.ImageRegistry, err error) {
		var (
			creds   *ecr.GetCredentialsResult
			decoded []byte
			parts   []string
		)

		if creds, err = ecr.GetCredentials(ctx, &ecr.GetCredentialsArgs{
			RegistryId: id,
		}); err != nil {
			return r, fmt.Errorf("failed to get ecr credentials: %w", err)
		}

		if decoded, err = base64.StdEncoding.DecodeString(creds.AuthorizationToken); err != nil {
			return r, fmt.Errorf("failed to decode ecr auth token: %w", err)
		}

		if parts = strings.Split(string(decoded), ":"); len(parts) != 2 {
			return r, fmt.Errorf("invalid ecr auth token, num parts: %d", len(parts))
		}

		return docker.ImageRegistry{
			Server:   creds.ProxyEndpoint,
			Username: parts[0],
			Password: parts[1],
		}, nil
	}).(docker.ImageRegistryOutput)

	for i := 0; i < 2; i++ {
		if _, err = docker.NewImage(ctx, fmt.Sprintf("%d", i), &docker.ImageArgs{
			Build: &docker.DockerBuildArgs{
				Context:      pulumi.String("../../.."),
				Dockerfile:   pulumi.String("../Dockerfile"),
				ExtraOptions: pulumi.ToStringArray([]string{"--platform=linux/amd64"}),
				Target:       pulumi.String("nginx"),
			},
			ImageName: repo.RepositoryUrl,
			SkipPush:  pulumi.Bool(true),
			// adding an output as a fix for: https://github.com/pulumi/pulumi-docker/issues/308
			Registry: info,
		}); err != nil {
			return fmt.Errorf("failed to pre-build docker image: %w", err)
		}
	}

	ctx.Export("repo_url", repo.RepositoryUrl)
	ctx.Export("registry_server", info.Server())
	return
}

func main() { pulumi.Run(run) }
```

### Expected Behavior

Should build two images without error

### Actual Behavior

It gives the following error:
```
Error saving credentials: error storing credentials - err: exit status 1, out: `error storing credentials - err: exit status 1, out: `The specified item already exists in the keychain.``
```

### Versions used

```
CLI          
Version      3.33.2
Go Version   go1.18.2
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.6.0
cloudflare  3.6.0
docker      3.2.0
go          unknown
random      4.6.0

Host     
OS       darwin
Version  12.2
Arch     arm64

This project is written in go (/usr/local/go/bin/go v1.18.3 darwin/arm64)

Current Stack: bug

TYPE                           URN
pulumi:pulumi:Stack            urn:pulumi:bug::reporthealth::pulumi:pulumi:Stack::reporthealth-bug
docker:image:Image             urn:pulumi:bug::reporthealth::docker:image:Image::0
docker:image:Image             urn:pulumi:bug::reporthealth::docker:image:Image::1
pulumi:providers:aws           urn:pulumi:bug::reporthealth::pulumi:providers:aws::default
aws:ecr/repository:Repository  urn:pulumi:bug::reporthealth::aws:ecr/repository:Repository::dockerbug


Found no pending operations associated with bug

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/advanderveer
User           advanderveer
Organizations  advanderveer

NAME                                        VERSION
github.com/apparentlymart/go-cidr           v1.1.0
github.com/pulumi/pulumi-aws/sdk/v5         v5.6.0
github.com/pulumi/pulumi-cloudflare/sdk/v3  v3.6.0
github.com/pulumi/pulumi-docker/sdk/v3      v3.2.0
github.com/pulumi/pulumi-random/sdk/v4      v4.6.0
github.com/pulumi/pulumi/sdk/v3             v3.31.1
github.com/stretchr/testify                 v1.7.1
go.uber.org/fx                              v1.17.1

Pulumi locates its logs in /var/folders/wx/kfpf_v7s2m5fvwnm0scmzdzm0000gn/T/ by default
```

### Additional context

There is an old issue that describes the same problem: https://github.com/pulumi/pulumi-docker/issues/24. There it seemed to be fixed through a PR but I'm running into this issues nonetheless.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkisk** [comment]
Thank you for filing this issue, it does look similar to the one you linked, we will look into it more.

**Comment by guineveresaenger** [comment]
Hi @advanderveer - I took a quick look around and I think the issue is related to a bad interaction with AWS ECR somehow triggering multiple docker logins, causing [something like this bug](https://github.com/docker/docker-credential-helpers/issues/37) with the `osxkeychain` to pop up.
Stack overflow reports this creeping up as recently as five months ago with ECR/docker, and suggests a few remedies:
https://stackoverflow.com/questions/70322012/docker-push-error-saving-credentials-error-storing-credentials-err-exit-stat
which links to [this issue in the docker cli](https://github.com/docker/cli/issues/1136)

Please let us know if they work for you locally or if we need to look into it further. 🙇‍♀️

**Comment by advanderveer** [comment]
@guineveresaenger  sorry for the late response. Apparently the GitHub notifications don't reach me that well. 

Good news is that I do seem to have run into a solution that works for me. I didn't try to compile it but it should work:
```
package main

import (
	"encoding/base64"
	"fmt"
	"strings"

	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/ecr"
	"github.com/pulumi/pulumi-docker/sdk/v3/go/docker"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func run(ctx *pulumi.Context) (err error) {
	var (
		repo *ecr.Repository
                // FIX: change the type of "info" to be `pulumi.Output` instead of `docker.ImageRegistryOutput`
		info pulumi.Output
	)

	if repo, err = ecr.NewRepository(ctx, "dockerbug", &ecr.RepositoryArgs{
		ImageTagMutability: pulumi.StringPtr("IMMUTABLE"),
	}); err != nil {
		return fmt.Errorf("failed to create repo: %w", err)
	}

	info = repo.RegistryId.ApplyT(func(id string) (r docker.ImageRegistry, err error) {
		var (
			creds   *ecr.GetCredentialsResult
			decoded []byte
			parts   []string
		)

		if creds, err = ecr.GetCredentials(ctx, &ecr.GetCredentialsArgs{
			RegistryId: id,
		}); err != nil {
			return r, fmt.Errorf("failed to get ecr credentials: %w", err)
		}

		if decoded, err = base64.StdEncoding.DecodeString(creds.AuthorizationToken); err != nil {
			return r, fmt.Errorf("failed to decode ecr auth token: %w", err)
		}

		if parts = strings.Split(string(decoded), ":"); len(parts) != 2 {
			return r, fmt.Errorf("invalid ecr auth token, num parts: %d", len(parts))
		}

               // FIX return a docker.ImageRegistryArgs type instead of docker.ImageRegistry
		return docker.ImageRegistryArgs{
			Server:   pulumi.String(creds.ProxyEndpoint),
			Username: pulumi.String(parts[0]),
			Password: pulumi.String(parts[1]),
		}, nil
	})
        // FIX: remove the interface assert that was on the previous line

	for i := 0; i < 2; i++ {
		if _, err = docker.NewImage(ctx, fmt.Sprintf("%d", i), &docker.ImageArgs{
			Build: &docker.DockerBuildArgs{
				Context:      pulumi.String("../../.."),
				Dockerfile:   pulumi.String("../Dockerfile"),
				ExtraOptions: pulumi.ToStringArray([]string{"--platform=linux/amd64"}),
				Target:       pulumi.String("nginx"),
			},
			ImageName: repo.RepositoryUrl,
			SkipPush:  pulumi.Bool(true),
			// adding an output as a fix for: https://github.com/pulumi/pulumi-docker/issues/308
			Registry: info,
		}); err != nil {
			return fmt.Errorf("failed to pre-build docker image: %w", err)
		}
	}

	ctx.Export("repo_url", repo.RepositoryUrl)
	ctx.Export("registry_server", info.Server())
	return
}

func main() { pulumi.Run(run) }

```


NOTE 1: I'm pretty sure that the way I did the above in the original issue I got from an official source. But I can't find it anyomore but it might be worth looking into and fix the documentation
NOTE 2: this is one of three blocking issues(!) I had to work around to get this provider to work (others ones being: https://github.com/pulumi/pulumi-docker/issues/310 and https://github.com/pulumi/pulumi-docker/issues/308). IMHO this providers needs some love or at least needs to be flagged at beta to warm developers of the possible time they need to invest to get things working

**Comment by advanderveer** [comment]
@jkisk @guineveresaenger Sorry for the late response, the GitHub notifications don't reach me that well apparently. 

Good news is that I found a workaround for my issue. I did read some of the links posted, but I'm not convinced this is the same issue. It seems to me that this provider just tries to login multiple times and that either Docker itself or my macOS keychain doesn't allow this (could be my specific setup but it's pretty common I would say).

Basically, the solution is to add a `sync.Once` to our codebase, and use it to make sure we actually only provide credentials to `NewImage` only once. The code from the original issue would need to look something like the code below.

NOTE: I would like to mention that this is one of three (!) workaround I had to use in my codebase to get this provider to work for my use case. The others being: https://github.com/pulumi/pulumi-docker/issues/310 and https://github.com/pulumi/pulumi-docker/issues/308. I think this provider needs some love or be marked as being in a beta 
state. Especially since Docker images  are such a common part of modern infrastructures.
```Go
package main

import (
	"encoding/base64"
	"fmt"
	"strings"
        "sync"

	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/ecr"
	"github.com/pulumi/pulumi-docker/sdk/v3/go/docker"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)


// credentialsOnce ensures that we only actually provide credentials for 
// docker to login, else we run into: https://github.com/pulumi/pulumi-docker/issues/362
var credentialsOnce = sync.Once{}

func run(ctx *pulumi.Context) (err error) {
	var (
		repo *ecr.Repository
		info docker.ImageRegistryOutput
	)

	if repo, err = ecr.NewRepository(ctx, "dockerbug", &ecr.RepositoryArgs{
		ImageTagMutability: pulumi.StringPtr("IMMUTABLE"),
	}); err != nil {
		return fmt.Errorf("failed to create repo: %w", err)
	}

	info = repo.RegistryId.ApplyT(func(id string) (r docker.ImageRegistry, err error) {
		var (
			creds   *ecr.GetCredentialsResult
			decoded []byte
			parts   []string
		)

		if creds, err = ecr.GetCredentials(ctx, &ecr.GetCredentialsArgs{
			RegistryId: id,
		}); err != nil {
			return r, fmt.Errorf("failed to get ecr credentials: %w", err)
		}

		if decoded, err = base64.StdEncoding.DecodeString(creds.AuthorizationToken); err != nil {
			return r, fmt.Errorf("failed to decode ecr auth token: %w", err)
		}

		if parts = strings.Split(string(decoded), ":"); len(parts) != 2 {
			return r, fmt.Errorf("invalid ecr auth token, num parts: %d", len(parts))
		}
                
                // FIX: we only provide the credentials once, to make sure docker is asked to login only once
		loginOnce.Do(func() {
			r.Server = creds.ProxyEndpoint 
			r.Username = parts[0]
			r.Password = parts[1]
		})

		return
	}).(docker.ImageRegistryOutput)

	for i := 0; i < 2; i++ {
		if _, err = docker.NewImage(ctx, fmt.Sprintf("%d", i), &docker.ImageArgs{
			Build: &docker.DockerBuildArgs{
				Context:      pulumi.String("../../.."),
				Dockerfile:   pulumi.String("../Dockerfile"),
				ExtraOptions: pulumi.ToStringArray([]string{"--platform=linux/amd64"}),
				Target:       pulumi.String("nginx"),
			},
			ImageName: repo.RepositoryUrl,
			SkipPush:  pulumi.Bool(true),
			// adding an output as a fix for: https://github.com/pulumi/pulumi-docker/issues/308
			Registry: info,
		}); err != nil {
			return fmt.Errorf("failed to pre-build docker image: %w", err)
		}
	}

	ctx.Export("repo_url", repo.RepositoryUrl)
	ctx.Export("registry_server", info.Server())
	return
}

func main() { pulumi.Run(run) }
```

**Comment by AaronFriel** [comment]
This issue should be resolved with the new implementation of the [Docker Image resource in v4](https://github.com/pulumi/pulumi-docker/releases/tag/v4.0.0)! See our blog post for more info: https://www.pulumi.com/blog/build-images-50x-faster-docker-v4/

The new version of the resource relies on Docker's Go SDK, and does not run side-effecting operations such as `docker login` commands to operate.

**Comment by gflarity** [comment]
@AaronFriel  I'm using Pulumi Docker 4.5.1 (Python) and I'm still getting the following error when I try to build a docker image with multiple targets:

```error reading build output: base: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

This might be a Docker issue rather than Pulumi-Docker, but it's not fixed.
